baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
  subtitle = "A work in progress"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4
